import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Button from "@/app/components/button/button";
import Navbar from "@/app/components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark bg-background">
            <body className={inter.className}>
                {children}
            </body>
        </html>
    );
}
